  //let score = '33'
//let score = '33abc'
//let score = null


//console.log(typeof score);
//console.log(typeof (score));

//let valueInNumber = Number(score)
//console.log(typeof valueInNumber);
//console.log(valueInNumberj);

let isLoggedIn = "ayan"

let BooleanIsIsLoggedIn = Boolean(isLoggedIn)
//console.log(BooleanIsIsLoggedIn);

// 1=> true; 0 => False
// "" => false
// "ayan" => true

let someNumber = 33

let stringNumber = String(someNumber)
//console.log(stringNumber); 
//console.log(typeof stringNumber);

//   *************************** Operations ******************


let value = 3
let negvalue = -value
//console.log(negvalue);

let str1 = "ayan"
let str2 = " mazumdar"
let str3 = str1 + str2
// console.log(str3);

// console.log("1" + 2);
// console.log(1 + "2");
// console.log("1"+ 2 + 3);
// console.log(1 + 2 + "2");

// console.log(true);
let gameCounter = 100
++gameCounter;
console.log(gameCounter);